### query transaction
GET http://localhost:8080/transaction/c5de3e889bec4b26bdbca0474eb93949


###Use Balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber":"1000000001",
  "amount": 3000
}

###Cancel Balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "6220780691cd4eeea68e49f623984785",
  "accountNumber":"1000000001",
  "amount": 300
}